// Copyright (c) 2025-2026, SFCGAL Team.
// SPDX-License-Identifier: LGPL-2.0-or-later

#ifndef SFCGAL_ALGORITHM_CHAMFER_H_
#define SFCGAL_ALGORITHM_CHAMFER_H_

#include <SFCGAL/Geometry.h>
#include <SFCGAL/LineString.h>
#include <SFCGAL/PolyhedralSurface.h>
#include <SFCGAL/Solid.h>
#include <SFCGAL/config.h>

#include <memory>
#include <vector>

namespace SFCGAL::algorithm {

/**
 * @brief Type of chamfer operation
 */
enum class ChamferType {
  FLAT, ///< Flat chamfer (straight cut)
  ROUND ///< Rounded fillet (circular arc cut)
};

/**
 * @brief Options for chamfer/fillet operations
 */
struct ChamferOptions {
  /// Type of operation: FLAT (chamfer) or ROUND (fillet)
  ChamferType type = ChamferType::FLAT;

  /// Primary radius (or width) of the chamfer/fillet
  double radius = 0.1;

  /// Secondary radius for asymmetric flat chamfers (if < 0, uses radius)
  /// Ignored for ROUND fillets (which are symmetric by definition here)
  double radius_y = -1.0;

  /// Number of segments for approximating the round fillet arc
  /// Higher values give smoother results but more geometry.
  int segments = 8;

  /// Epsilon tolerance for matching the input edge to the solid's edges
  double epsilon = 1e-6;
};

/**
 * @brief Apply a chamfer or fillet operation to a solid along a specified edge.
 *
 * This function performs a 3D boolean difference between the input solid and a
 * "cutter volume" generated by sweeping a profile along the edge.
 *
 * The cutter profile is automatically oriented to align with the faces incident
 * to the edge, ensuring the material is removed correctly from the corner.
 *
 * @param solid The input 3D Solid or PolyhedralSurface to modify.
 * @param edge The 3D LineString or MultiLineString representing the edge(s) to
 * chamfer. These edges must geometrically coincide with edges of the solid.
 * @param options Configuration for the chamfer (radius, type, etc.)
 * @return std::unique_ptr<Geometry> The modified solid with the chamfer
 * applied.
 * @throws std::invalid_argument If inputs are invalid or edge is not found on
 * solid.
 */
SFCGAL_API auto
chamfer(const Geometry &solid, const Geometry &edge,
        const ChamferOptions &options = {}) -> std::unique_ptr<Geometry>;

} // namespace SFCGAL::algorithm

#endif // SFCGAL_ALGORITHM_CHAMFER_H_
