# This image is used by pysfcgal to generate linux wheels
# The wheels need to be compatible with glibc 2.35 (ubuntu 22.04 and forward)
# Keep bookworm to ensure it
FROM gcc:13-bookworm AS builder

WORKDIR /SFCGAL

COPY src ./src
COPY test ./test
COPY sfcgalop ./sfcgalop
COPY CMakeLists.txt SFCGALConfig.cmake.in sfcgal.pc.in sfcgal-config.in ci/debian/before_install.sh ./

ARG CGAL_VERSION
ENV CI_PROJECT_DIR=/opt
RUN ./before_install.sh $CGAL_VERSION

RUN CGAL_DIR=${CI_PROJECT_DIR}/CGAL cmake -B build \
    -DSFCGAL_BUILD_TESTS=ON \
    -DCMAKE_C_COMPILER=/usr/local/bin/gcc \
    -DCMAKE_CXX_COMPILER=/usr/local/bin/g++ \
    -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build -j$(nproc)

FROM debian:bookworm-slim AS run

RUN apt update -qq && \
    apt install --no-install-recommends --yes libboost-atomic1.74.0 libboost-program-options1.74.0 libboost-serialization1.74.0 libboost-test1.74.0 libboost-thread1.74.0 libmpfr6 libgmpxx4ldbl

ENV LD_LIBRARY_PATH=/usr/local/lib64

WORKDIR /SFCGAL
COPY --from=builder /SFCGAL/build /SFCGAL/build
COPY --from=builder /usr/local/lib64 /usr/local/lib64
COPY docker/entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh"]
